INSERT  INTO
	t_s_user
      ( 
      email                         
      ,mobilePhone                    
      ,officePhone                    
      ,signatureFile                  
      ,id                             
      ,update_name                    
      ,update_date                    
      ,update_by                      
      ,create_name                    
      ,create_date                    
      ,create_by                      
      ) 
values
      (
      :tSUserP3Mail.email
      ,:tSUserP3Mail.mobilephone
      ,:tSUserP3Mail.officephone
      ,:tSUserP3Mail.signaturefile
      ,:tSUserP3Mail.id
      ,:tSUserP3Mail.updateName
      ,:tSUserP3Mail.updateDate
      ,:tSUserP3Mail.updateBy
      ,:tSUserP3Mail.createName
      ,:tSUserP3Mail.createDate
      ,:tSUserP3Mail.createBy
      )