INSERT  INTO
	t_s_base_user
      ( 
      ID                            
      ,activitiSync                   
      ,browser                        
      ,password                       
      ,realname                       
      ,signature                      
      ,status                         
      ,userkey                        
      ,username                       
      ,departid                       
      ,delete_flag                    
      ) 
values
      (
      :tSBaseUserP3Mail.id
      ,:tSBaseUserP3Mail.activitisync
      ,:tSBaseUserP3Mail.browser
      ,:tSBaseUserP3Mail.password
      ,:tSBaseUserP3Mail.realname
      ,:tSBaseUserP3Mail.signature
      ,:tSBaseUserP3Mail.status
      ,:tSBaseUserP3Mail.userkey
      ,:tSBaseUserP3Mail.username
      ,:tSBaseUserP3Mail.departid
      ,:tSBaseUserP3Mail.deleteFlag
      )